# use_thin_strokes = true

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x676767"
blue = "0x6871ff"
cyan = "0x5ffdff"
green = "0x5ff967"
magenta = "0xff76ff"
red = "0xff6d67"
white = "0xfeffff"
yellow = "0xfefb67"

[colors.normal]
black = "0x000000"
blue = "0x0225c7"
cyan = "0x00c5c7"
green = "0x00c200"
magenta = "0xc930c7"
red = "0xc91b00"
white = "0xc7c7c7"
yellow = "0xc7c400"

[font]
size = 18.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
opacity = 0.9
option_as_alt = "OnlyLeft"

[window.padding]
x = 10
y = 10
